# Configuration for: Analysis Flow (Project Alpha)
# File: configs/variables/dept_project_alpha/analysis_config_dept_project_alpha.yaml
# Corresponding Prefect Variable Name (proposed): dept_project_alpha_analysis_config
# department_name: "Project Alpha"
# subflow_configs:
#   category_x: {}
