# Configuration for: Ingest Web Page Link Scraping (Project Alpha)
# File: configs/variables/dept_project_alpha/ingestion/web_page_link_scraping/ingest_web_page_link_scraping_config_dept_project_alpha.yaml
# Corresponding Prefect Variable Name (proposal - requires setup script update): dept_project_alpha_ingestion_web_page_link_scraping_config

# Define parameters needed by the 'ingest_web_page_link_scraping_flow_dept_project_alpha.py' flow.
# This structure will likely be loaded into a Prefect Variable (e.g., 'dept_project_alpha_ingestion_web_page_link_scraping_config')
# or included within a larger department/stage configuration Variable.

# Example Parameters:
data_source_name: "dept_project_alpha_ingestion_web_page_link_scraping" # For manifest tasks
source_url: "http://example.com/dept_project_alpha/ingestion/web_page_link_scraping/data.csv"
# api_endpoint: null
# target_table: "processed_web_page_link_scraping"
# scraping_selectors:
#   - container: ".item-list"
#     link: "a.data-link[href]"
# processing_threshold: 0.95
